### PR TITLE
fix invalid date time format 

### LINKED ISSUE #9: invalid date time format
Kio Client generates url "https://kio.stups.zalan.do/apps?modified_before=2016-07-14T15:04:22.6+02:00" which results in 400 Bad Request

"Value \"2016-07-14T15:04:22.6 02:00\" in query->modified_before (not required) cannot be used as type 'string' with format 'date-time' because it cannot be transformed: Invalid format: \"2016-07-14T15:04:22.6 02:00\" is malformed at \" 02:00\"."

### PR DESCRIPTION
**Pull request by ljaeckel**
fixes #9

### CODE REVIEW

File: kio-client-java-spring/src/test/java/org/zalando/stups/clients/kio/spring/RestTemplateKioOperationsTest.java [hunk 1]
```diff
@@ -95,8 +94,8 @@ public void testGetRangeOfApplications() throws ParseException {
         final ZonedDateTime modifiedAfter = now().minusDays(2);
 
         mockServer.expect(requestTo(
-                format("%s/apps?modified_before=%s&modified_after=%s", //
-                        BASE_URL, toIsoString(modifiedBefore), toIsoString(modifiedAfter)))) //
+                UriComponentsBuilder.fromHttpUrl(format("%s/apps?modified_before=%s&modified_after=%s", //
```
Comment (harti2006) [inline kio-client-java-spring/src/test/java/org/zalando/stups/clients/kio/spring/RestTemplateKioOperationsTest.java]: can you please implement the test differently than the production code? otherwise it shows nothing (which is a as bad as my version before)

e.g. url-encode only the strings for the date times

**Comment by harti2006** [comment]
`UriComponents::encode` is a nice finding :)

**Comment by harti2006** [comment]
:+1:

**Comment by harti2006** [comment]
:+1:

File: kio-client-java-spring/src/test/java/org/zalando/stups/clients/kio/spring/RestTemplateKioOperationsTest.java [hunk 2]
```diff
@@ -94,9 +92,10 @@ public void testGetRangeOfApplications() throws ParseException {
         final ZonedDateTime modifiedBefore = now().plusDays(1);
         final ZonedDateTime modifiedAfter = now().minusDays(2);
 
-        mockServer.expect(requestTo(
-                format("%s/apps?modified_before=%s&modified_after=%s", //
-                        BASE_URL, toIsoString(modifiedBefore), toIsoString(modifiedAfter)))) //
+        mockServer.expect(requestTo(format("%s/apps?modified_before=%s&modified_after=%s", //
+                BASE_URL,
+                toIsoString(modifiedBefore).replaceAll("\\+", "%2B"),  //
```
Comment (akhomchenko) [inline kio-client-java-spring/src/test/java/org/zalando/stups/clients/kio/spring/RestTemplateKioOperationsTest.java]: I don't like this `replaceAll` at all

Comment (harti2006) [inline kio-client-java-spring/src/test/java/org/zalando/stups/clients/kio/spring/RestTemplateKioOperationsTest.java]: I would not use this in production code, either. However for testing, I think it is fine. Another good option would imho be, to use hardcoded values for the date times. This makes it even more obvious how the final result should look like.
e.g.

``` java
final ZonedDateTime modifiedBefore = ZonedDateTime.parse("2016-07-19T00:00:00.000Z");
final ZonedDateTime modifiedAfter = ZonedDateTime.parse("2016-06-11T00:00:00.000+02:00");
mockServer.expect(requestTo(format("%s/apps?modified_before=%s&modified_after=%s", 
        BASE_URL,
        "2016-07-19T00:00:00.000Z",  
        "2016-06-11T00:00:00.000%2B02:00"))) 
        .andExpect(method(GET)) 
        .andRespond(withSuccess(resource("/getApplications"), APPLICATION_JSON));
```

File: kio-client-java-spring/src/main/java/org/zalando/stups/clients/kio/spring/DateTimeUtils.java [hunk 3]
```diff
@@ -15,15 +15,18 @@
...
 
-import static java.time.format.DateTimeFormatter.ISO_OFFSET_DATE_TIME;
-
+import java.time.format.DateTimeFormatter;
 import java.time.temporal.TemporalAccessor;
 
 public final class DateTimeUtils {
 
-    private DateTimeUtils() { }
+    public static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSZZZ");
```
Comment (harti2006) [inline kio-client-java-spring/src/main/java/org/zalando/stups/clients/kio/spring/DateTimeUtils.java]: should be `private` ;-)

Comment (harti2006) [inline kio-client-java-spring/src/main/java/org/zalando/stups/clients/kio/spring/DateTimeUtils.java]: please use the pattern with `XXX` as zone offset part. See JavaDocs at class `DateTimeFormatter`:

> Offset X and x: This formats the offset based on the number of pattern letters. One letter outputs just the hour, such as '+01', unless the minute is non-zero in which case the minute is also output, such as '+0130'. Two letters outputs the hour and minute, without a colon, such as '+0130'. Three letters outputs the hour and minute, with a colon, such as '+01:30'. Four letters outputs the hour and minute and optional second, without a colon, such as '+013015'. Five letters outputs the hour and minute and optional second, with a colon, such as '+01:30:15'. Six or more letters throws IllegalArgumentException. Pattern letter 'X' (upper case) will output 'Z' when the offset to be output would be zero, whereas pattern letter 'x' (lower case) will output '+00', '+0000', or '+00:00'

**Comment by harti2006** [comment]
:+1:

**Comment by ljaeckel** [comment]
👍
